version: '3.4'
services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www
      - ./docker/nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
      - "433:433"
    env_file:
      - variables.env

  php:
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.docker
    volumes:
      - ./www:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    env_file:
      - variables.env

  php-cli:
    build:
      context: ./
      dockerfile: ./docker/php-cli/php-cli.docker
    volumes:
      - ./www:/var/www
      - ./docker/php-cli/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    tty: true
    ports:
      - "6001:6001"
    environment:
      - PHP_IDE_CONFIG=serverName=localhost

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - variables.env
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=mash_group
      - RABBITMQ_DEFAULT_PASS=mash_group
    ports:
      - "5672:5672"
      - "15672:15672"



